### PR TITLE
RHIDP-1025: Migrate Janus IDP customization provider repo to redhat-developers org

### PR DESCRIPTION
**Pull request by Zaperex**
### Description
Update references and links to the `backstage-customization-provider` repository in the janus-idp org to point to the `red-hat-developer-hub-customization-provider` repository in the redhat-developers org

### JIRA issue
Fixes [RHIDP-1025](https://issues.redhat.com/browse/RHIDP-1025)

### CODE REVIEW

**Comment by nickboldt** [comment]
Looks good, though I notice we have refs to `janus-idp/backstage-showcase` in https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/147/files#diff-42a14a545e1fe0d842c35612404560440d58ed9b514d7b45ee0f0646611a4384R18 but that can be cleaned up in https://issues.redhat.com/browse/RHIDP-1022

/approve

**Review by linfraze — APPROVED** [review]
the replacements lgtm

**Pull request merged**
