### PR TITLE
RHIDP-2842 : chore(gh action): possible fix to pull...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

chore(gh action): possible fix to pull before pushing, so we get fewer collisions when lots of PRs are being generated/merged concurrently

Signed-off-by: Nick Boldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A (or see commit message above for issue number)

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by briandooley** [comment]
Assessing this in [RHIDP-2842](https://issues.redhat.com/browse/RHIDP-2842).

**Review by themr0c — APPROVED** [review]
Why not. Let's see if it fixes race conditions.

**Comment by nickboldt** [comment]
Let's hold on merging this until after 1.2 GA in case this needs to be backed out

**Comment by briandooley** [comment]
Docs team will look into merging this next Monday July 1 and see if any issues caused.

**Comment by themr0c** [comment]
It does not work well on pull requests: the gh-pages branch is missing on user forks.

**Comment by nickboldt** [comment]
> It does not work well on pull requests: the gh-pages branch is missing on user forks.

what error do you get? Can you provide a link to a PR or action that failed?

**Pull request merged**
