### PR TITLE
fix: No duplicate title

### PR DESCRIPTION
**Pull request by themr0c**
The title is already defined in the assembly (consistent with other titles).

Fixes the build in Pantheon.

**IMPORTANT: Do Not Merge - To be merged by Docs Team Only**

**Version(s):**

Add the relevant labels to the Pull Request.
**Issue:**

### CODE REVIEW

**Review by jmagak — APPROVED** [review]
lgtm

**Comment by Gerry-Forde** [comment]
@themr0c Should the Preface still appear in the preview of this title?
c.c. @jmagak

**Comment by themr0c** [comment]
@Gerry-Forde I noticed that too. Ccutil is not handling properly the metadata. This is the next shift-left iteration.

**Pull request merged**
