### PR TITLE
RHIDP-2405 : Added the content explaining vulnerabilities, SBOMs, and EC

### PR DESCRIPTION
**Pull request by gtrivedi88**
Purpose: To resolve [RHIDP-2405](https://issues.redhat.com/browse/RHIDP-2405)

Content for preview: https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-279/plugin-rhdh/#installation-and-configuration-tekton

SME review completed by  @karthikjeeyar in this PR: https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/72

QE review:

Peer review: @themr0c

### CODE REVIEW

**Comment by christophe-f** [comment]
This seems to be a documentation for RHTAP and not RHDH

**Comment by gtrivedi88** [comment]
> This seems to be a documentation for RHTAP and not RHDH

@christophe-f This doc covers this use case: By default, a user in RHDH will see no data in the Vulnerability column and Output icons. To see the data, the user has to either subscribe to RHTAP or manually configure some settings. This doc talks about those manual settings. 

cc  @karthikjeeyar

**Comment by christophe-f** [comment]
This was a bug in the plugin and that column should not be visible anymore.

**Comment by gtrivedi88** [comment]
> This was a bug in the plugin and that column should not be visible anymore.

Got you. Thank you for the information.
Question - The existing Tekton ends indicating that  a user will see vulnerabilities. Do you think we should add a note or something indicating that you must Subscribe to RHTAP to view this?

Link to existing doc: https://access.redhat.com/documentation/en-us/red_hat_developer_hub/1.1/html/administration_guide_for_red_hat_developer_hub/rhdh-installing-dynamic-plugins#installation-and-configuration-tekton

**Comment by linfraze** [comment]
> > This was a bug in the plugin and that column should not be visible anymore.
> 
> Got you. Thank you for the information. Question - The existing Tekton ends indicating that a user will see vulnerabilities. Do you think we should add a note or something indicating that you must Subscribe to RHTAP to view this?
> 
> Link to existing doc: https://access.redhat.com/documentation/en-us/red_hat_developer_hub/1.1/html/administration_guide_for_red_hat_developer_hub/rhdh-installing-dynamic-plugins#installation-and-configuration-tekton

If a note is needed, can you please create a Jira ticket for the RHDH Docs Team in the RHIDP project? Adding the Documentation component and/or RHIDP - Documentation Team field assigns the task to the Docs Team. Thanks!

**Comment by briandooley** [comment]
@gtrivedi88 Is this PR still needed?

**Comment by gtrivedi88** [comment]
@linfraze  @briandooley I'll follow up again with the SME on what we need to do.
I don't think we need this PR. Having said that, I think we need to find a way to inform the customers about RHTAP.

cc @tshearon FYI

**Comment by gtrivedi88** [comment]
@linfraze @briandooley  Just had a meeting with Tanya. Based on that SME comments:
1. I'll be closing this PR
2. We need a new Jira in to add a note or additional resources at the end of this page: https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.2/html/configuring_plugins_in_red_hat_developer_hub/rhdh-installing-dynamic-plugins#rhdh-installing-dynamic-plugins

Note/Additional resources would be like: To view Vulnerabilities, SBOMs, and Enterprise Contracts, you must susbscribe to Red Hat Trusted Application Pipeline.

Without this note the current doc is not correct.

You can assign this task to me or someone from RHDH team. For now, I'm going to close this PR and  the associated Jira task.

let me know if you have questions.

**Comment by briandooley** [comment]
new jira is [RHIDP-3106](https://issues.redhat.com/browse/RHIDP-3106).

**Pull request closed without merging**
