### PR TITLE
Fix bug #120

### PR DESCRIPTION
**Pull request by abrennan89**
Fixes https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/issues/120

### CODE REVIEW

**Comment by hmanwani-rh** [comment]
@abrennan89 Please rebase the branch and cherry-pick these changes to 1.0.x and 1.1.x branches as well.

**Comment by abrennan89** [comment]
@hmanwani-rh the only branch names I see are `rhdh-1.0` and `1.1.x` - are these correct?

**Comment by jerolimov** [comment]
For @abrennan89  /cc @kadel 

/cherrypick 1.1.x

**Comment by hmanwani-rh** [comment]
> @hmanwani-rh the only branch names I see are `rhdh-1.0` and `1.1.x` - are these correct?

Yep, my bad. I meant `rhdh-1.0` and `1.1.x`.

**Comment by hmanwani-rh** [comment]
Additionally, this pull request has some conflicts. Would you mind resolving them, and then we can proceed with merging it?

**Pull request merged**
