### PR TITLE
chore(dyn plugins): hide argo-cd common plugin as it has no configuration (used by argo-cd plugin); reorient the redhat- prefixed and community plugin entries to have cleaner names (RHIDP-3397)

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

chore(dyn plugins): hide argo-cd common plugin as it has no configuration (used by argo-cd plugin); reorient the redhat- prefixed and community plugin entries to have cleaner names

Also replace "msgraph" with "MS Graph"

Signed-off-by: Nick Boldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
RHIDP-3397

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by Gerry-Forde — COMMENTED** [review]
@nickboldt 

Just one small issue...I know the plugin names are generated from the package name but can we tweak Msgraph to MS Graph in the script, or if not, we could manually update it for 1.3?

**Comment by nickboldt** [comment]
Manual updates are discouraged as they'll be overridden when we regenerate the table. 

However it's very easy to add special mappings for the names, like "msgraph" to "MS Graph".

https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/463/commits/34d9acf000d4cbeea7cc7622e93c21e6453987ff

Good catch -- let me know if you find other mappings / special cases that should be added to the `titlecase()` method.

**Review by Gerry-Forde — APPROVED** [review]

**Comment by nickboldt** [comment]
automated cherypick failed (because plugins versions are different in 1.3.x vs. main) so here's a manual PR: https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/465

**Pull request merged**
