### PR TITLE
Add supported platform

### PR DESCRIPTION
**Pull request by jmagak**
**IMPORTANT: Do Not Merge - To be merged by Docs Team Only**

**Version(s):** 1.4

Add the relevant labels to the Pull Request.
**Issue:** 
https://issues.redhat.com/browse/RHIDP-4699
Related PR: https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/661

### CODE REVIEW

**Review by pabel-rh — APPROVED** [review]

**Review by themr0c — APPROVED** [review]

**Comment by themr0c** [comment]
Oh! The PR got merged as soon as I removed the draft state. Auto-merge was enabled?

**Comment by themr0c** [comment]
@pabel-rh can you manually cherry-pick to the release-1.3 branch?

**Comment by themr0c** [comment]
release-1.4 is OK now

@pabel-rh can you manually cherry-pick to the release-1.3 branches this and https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/661 (in one single PR)?

**Pull request merged**
