### PR TITLE
chore: [1.1.x] bump plugin versions in 1.1.1

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

chore: bump plugin versions in 1.1.1 - RHIDP-1702 / RHIDP-1694

Signed-off-by: Nick Boldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
* https://issues.redhat.com/browse/RHIDP-1702 
* https://issues.redhat.com/browse/RHIDP-1694

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by hmanwani-rh — APPROVED** [review]

**Comment by hmanwani-rh** [comment]
@nickboldt I think we also need QE to review these changes. 
@josephca Could you please take a moment and review the changes in this PR?

**Comment by Gerry-Forde** [comment]
@nickboldt Is the "single source of truth" for plugin versions/support still the following: https://docs.google.com/spreadsheets/d/1dNUAGTeosEzreX9fxFTW1Vq3oGCbHroZ_DFEL8sjfjY

Does it need to be updated for 1.1.1 or is there an alternative reference document?

**Comment by nickboldt** [comment]
The linked issue RHIDP-1702 contains the latest plugins.

I'll update the spreadsheet one more time, if that makes it simpler.

**Comment by Gerry-Forde** [comment]
@nickboldt One other question around updting the plugin versions, is there any need to reference somewhere the original versions that were shipped with 1.1.0?

**Comment by nickboldt** [comment]
What if in the RN we just link to this PR so anyone can see the old versions if they care? https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/133/files shows the changes pretty clearly.

**Pull request merged**
