### PR TITLE
RHIDP-4814: Move observe related content to new titles

### PR DESCRIPTION
**Pull request by hmanwani-rh**
**IMPORTANT: Do Not Merge - To be merged by Docs Team Only**

**Version(s):**
 1.4

**Issue:**
https://issues.redhat.com/browse/RHIDP-4814

**Link to docs preview:**
Find the link within the PR

**Reviews:**
- [x] SME: @kim-tsao 
- [ ] QE: @ mention assignee
- [x] Docs review: @pabel-rh 

**Additional information:**

### CODE REVIEW

**Comment by kim-tsao** [comment]
Under the Monitoring and Logging topic, should the chapter numbering be continuous? 
image


There are three parts, but I would expect the chapters under each part should be reset. e.g. 

Part 1:
* chapter 1
* chapter 2

Part 2:
* chapter 1 
* chapter 2

**Comment by kim-tsao** [comment]
Should we consider having two parts for Telemetry Data Collection?  One for helm and one for operator?  That way,  the instructions are fully contained under the relevant install methods.  As a user who may be scrolling through the docs, it might be annoying to have to skip through the parts that are of no interest

e.g.

I Telemetry Data Collection using the Helm Chart
   1.  Disabling telemetry data collection in RHDH
   2.  Enabling telemetry data collection in RHDH
   3.  Customizing telemetry Segment source

II  Telemetry Data Collection using the Operator
   1.  Disabling telemetry data collection in RHDH
   2.  Enabling telemetry data collection in RHDH
   3.  Customizing telemetry Segment source

**Comment by hmanwani-rh** [comment]
> Should we consider having two parts for Telemetry Data Collection? One for helm and one for operator? That way, the instructions are fully contained under the relevant install methods. As a user who may be scrolling through the docs, it might be annoying to have to skip through the parts that are of no interest
> 
> e.g.
> 
> I Telemetry Data Collection using the Helm Chart
> 
> 1. Disabling telemetry data collection in RHDH
> 2. Enabling telemetry data collection in RHDH
> 3. Customizing telemetry Segment source
> 
> II Telemetry Data Collection using the Operator
> 
> 1. Disabling telemetry data collection in RHDH
> 2. Enabling telemetry data collection in RHDH
> 3. Customizing telemetry Segment source

@kim-tsao Thank you for reviewing the PR and sharing your feedback. I really appreciate the suggested structure. That said, I was also considering keeping the structure consistent with other titles, where we describe all the procedures in the same format—starting with the procedure for the Operator, followed by the procedure for the Helm chart.

However, I’d be happy to discuss this with Preeti and get her input on whether we can adopt this structure. If she agrees, we may need to apply it to other titles as well. I'll keep you updated.

**Review by pabel-rh — APPROVED** [review]

**Comment by hmanwani-rh** [comment]
> Under the Monitoring and Logging topic, should the chapter numbering be continuous? image
> 
> There are three parts, but I would expect the chapters under each part should be reset. e.g.
> 
> Part 1:
> 
> * chapter 1
> * chapter 2
> 
> Part 2:
> 
> * chapter 1
> * chapter 2

@kim-tsaoI’ve reorganized the content by removing the parts and converting them into chapters as follows: 

image

**Pull request merged**
