### PR TITLE
chore(dynamic plugins): fixed namespace for community plugins and pagerduty (RHIDP-4079)

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

chore(dynamic plugins): regen table with fixed namespace for community plugins and pagerduty

Signed-off-by: Nick Boldt <nboldt@redhat.com>

fix: use backstage-community/plugin- instead of incorrect
backstage/community-plugin-

Signed-off-by: Nick Boldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?

https://issues.redhat.com/browse/RHIDP-4079

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by nickboldt** [comment]
Explaining this fix:

the old pattern of
`@backstage/community-plugin-`

doesn't work when you search for that at [npmjs.com](http://npmjs.com/)

but the new pattern of
`@backstage-community/plugin-`

does work. For example... 

https://www.npmjs.com/package/@backstage-community/plugin-3scale-backend (works)
vs.
https://www.npmjs.com/package/@backstage/community-plugin-3scale-backend (404'd) (edited)

**Review by gwynnemonahan — COMMENTED** [review]
/lgtm

**Review by gwynnemonahan — APPROVED** [review]
/lgtm

**Review by Gerry-Forde — APPROVED** [review]
/lgtm

**Comment by nickboldt** [comment]
manual cherrypick to `release-1.3` branch in https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/511

**Pull request merged**
