### PR TITLE
RHIDP-1774: Fix 3Scale environment variables in documentation

### PR DESCRIPTION
**Pull request by jesuino**

### CODE REVIEW

**Comment by hmanwani-rh** [comment]
@jesuino This PR also needs to cherry-pick to 1.1 branch to reflect in the 1.1 docs.

**Comment by jesuino** [comment]
@hmanwani-rh Thanks for letting me know. Do we also need a PR for 1.1.x?

Here's the PR

https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/148

**Comment by hmanwani-rh** [comment]
@jesuino Please rebase this PR and I'll merge it

**Comment by jesuino** [comment]
@hmanwani-rh done

**Pull request merged**
