### PR TITLE
chore(release notes): 1.3.2/1.3.3 release notes (RHIDP-4909)

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

chore(release notes): 1.3.2-1.3.3 release notes (RHIDP-4909)

Signed-off-by: Nick Boldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A (or see commit message above for issue number)

### How to test this PR?
N/A

### PR Checklist

As the author of this Pull Request I made sure that:

- [x] Code produced is complete
- [ ] Code builds without errors
- [ ] Tests are covering the bugfix
- [ ] Relevant user documentation updated
- [ ] Relevant contributing documentation updated

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by themr0c — APPROVED** [review]

**Comment by themr0c** [comment]
Added the do-not-merge/hold label to avoid someone merging this pull request before the 1.3.2 release.

**Comment by nickboldt** [comment]
After Kim's final review, I've added one more CVE to the pile.

Preview: https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-731/rel-notes-rhdh/#_red-hat-developer-hub-1-3-2

Also added one more known issue: 

https://issues.redhat.com/browse/RHIDP-3396

and removed one:

https://issues.redhat.com/browse/RHIDP-3931

**Comment by nickboldt** [comment]
@themr0c  According to the results of the python RN script, https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/731/files#diff-c1ddcd44eb3d2647b4a4574b3658dd05f151ad681a1d7ed49dd0dadb9e6d62d7L14 shows that https://issues.redhat.com/browse/RHIDP-3931 was fixed in this release but the fix version is ONLY 1.4.

We might have a bug in the python code. :(

**Comment by themr0c** [comment]
@nickboldt If I run now `./modules/release-notes/single-source-release-notes.py` on the release-1.3 branch, it *removes* `modules/release-notes/snip-known-issue-rhidp-3931.adoc`. Therefore I believe the script behavior is OK, and the presence of this Jira in the release notes was caused by wrong metadata in Jira.

**Comment by nickboldt** [comment]
> @nickboldt If I run now `./modules/release-notes/single-source-release-notes.py` on the release-1.3 branch, it _removes_ `modules/release-notes/snip-known-issue-rhidp-3931.adoc`. Therefore I believe the script behavior is OK, and the presence of this Jira in the release notes was caused by wrong metadata in Jira.

OK but https://issues.redhat.com/browse/RHIDP-3931 is unresolved so it's a KI for 1.3. 

So removing it from the list of KIs is WRONG.

**Comment by nickboldt** [comment]
Since I've had to bump the CSV to 1.3.3 we might want to bump the version of the RN updates and these params to 1.3.3:

```
:product-bundle-version: 1.3.2
:product-chart-version: 1.3.2
```

Waiting to see if we can get approvals for the new FBC RPA push process...

**Review by Fortune-Ndlovu — APPROVED** [review]

**Pull request merged**
