### PR TITLE
RHIDP-3515: Move authentication related content to a new category

### PR DESCRIPTION
**Pull request by themr0c**
Move authentication related content to a new category

**Version(s):** 1.3

**Issue:** https://issues.redhat.com/browse/RHIDP-3515

**Link to docs preview:** 

* https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-435/authentication/

* https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-435/authorization/

**Reviews:**
- [ ] SME: @ mention assignee
- [ ] QE: @ mention assignee
- [ ] Docs review: @ mention assignee

**Additional information:**

### CODE REVIEW

**Comment by nickboldt** [comment]
It's a bit of a long title especially compared to all the other books:
image

What's wrong with calling it just Authentication, since you need BOTH types of auth together to be effective? 

image

Or even better, put this in with the existing Getting Started or Admin guide since you can't use RHDH without getting auth configuration, and the person enjoying the content journey of auth config is an administrator?

I get that the new ContentX strategy is to make it harder to search through a single document for keywords, in that you're forcing people to pick a doc from a list of several ones 

image

vs.

image

But this whole "tiny books for every topic" seems counterintuitive to how administrators search for help. Just my $0.02 based on how I personally do it/ops/dev work. :shrug: 

Process question: 

Why does the description of this issue have 3 checkboxes AND there are also 3 subtask jiras to complete? Seems duplicative. Are the boxes there just symobolically to remind people to check the JIRAs?

https://issues.redhat.com/browse/RHIDP-3515

**Review by nickboldt — COMMENTED** [review]
given no content is changing, just being reorged, +1 to merge... 

... despite my hesitation to force users to open multiple books to get started with a RHDH install, deployment, and auth config.

**Review by nickboldt — APPROVED** [review]

**Comment by themr0c** [comment]
I understand your hesitations. I have the same. This is part of a general plan to cut big guides in smaller pieces across all products, that went from recommendation to enforcement. It is a known fact that with the current customer portal design, the user experience is being damaged. We received that promise that the new design that we expect all soon will fix that and enhance searchability.

**Pull request merged**
