### PR TITLE
RHIDP-3078: Add example curl command for nested conditional policies

### PR DESCRIPTION
**Pull request by dzemanov**
**Version(s):**
1.3

**Issue:**
[RHIDP-3078](https://issues.redhat.com/browse/RHIDP-3078)

### CODE REVIEW

**Review by AndrienkoAleksandr — COMMENTED** [review]
Looks good to me.

**Comment by AndrienkoAleksandr** [comment]
Optional: can you apply example with role creation, please?

**Review by hmanwani-rh — APPROVED** [review]

**Comment by hmanwani-rh** [comment]
@PatAKnight Could you please take a look at this PR and share your comments?

**Review by PatAKnight — APPROVED** [review]
lgtm

**Review by gustavolira — APPROVED** [review]

**Pull request merged**
