### PR TITLE
RHIDP-4090: Fixed typo

### PR DESCRIPTION
**Pull request by pabel-rh**
**IMPORTANT: Do Not Merge - To be merged by Docs Team Only**

**Version(s):** 1.2, 1.3

**Issue:** RHIDP-4090

**Reviews:**
- [x] SME: @johnmcollier 
- [x] Docs review: @hmanwani-rh or @jmagak

### CODE REVIEW

**Review by jmagak — APPROVED** [review]
LGTM, @pabel-rh

**Comment by hmanwani-rh** [comment]
@pabel-rh Before merging this PR, we’ll need approval from John.
@johnmcollier Could you please review this minor PR and provide your approval so that we can proceed with the merge?

**Comment by hmanwani-rh** [comment]
@pabel-rh Please rebase your branch

**Pull request merged**
