### PR TITLE
RHIDP-2824 : chore(dynamic-plugins) generate dynamic plugins table

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

chore(dynamic-plugins) generate dynamic plugins from content in janus plugins and showcase repos; instead of description, link to npmjs.com package

Signed-off-by: Nick Boldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?

* https://issues.redhat.com/browse/RHIDP-2519 
* https://issues.redhat.com/browse/RHIDP-2824
* https://issues.redhat.com/browse/RHIDP-2834
* https://issues.redhat.com/browse/RHIDP-2835
* https://issues.redhat.com/browse/RHIDP-2836
* https://issues.redhat.com/browse/RHIDP-2837
* https://issues.redhat.com/browse/RHIDP-2838
* https://issues.redhat.com/browse/RHIDP-2839
* https://issues.redhat.com/browse/RHIDP-2840

Summarizing the changes in this PR:

* 5 new plugins added https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/1.2.x/rel-notes-rhdh/#_new-plugins-included-in-red-hat-developer-hub-1-2
* 1 plugin removed (the dynamic plugins info plugin is not a dynamic plugin – it's a static plugins that informs a user about which dynamic plugins are present
* updated plugin versions from what was in 1.1.1 to the latest included in 1.2.0
* some minor reformatting to remove the description column (manually maintained) in favour of links to the package readmes on npmjs.com
* content is now generated via script using information from package.json and dynamic-plugins.default.json

### How to test this PR?
run the script to see the output. Or look at the changes to `modules/dynamic-plugins/rhdh-supported-plugins.adoc` in this PR! 

```
./modules/dynamic-plugins/rhdh-supported-plugins.sh -b main --clean
./build/scripts/build.sh; google-chrome titles-generated/main/plugin-rhdh/index.html
```
### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by nickboldt** [comment]
Preview at https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-300/plugin-rhdh/#con-preinstalled-dynamic-plugins

Some ideas to further improve: 

* split table by support levels (RH GA, RH TP, Community)
* split table so scaffolders are in a separate table from the other plugins
* split front end, back end, and scaffolders into 3 tables
* combine name, role, and version into a single column, eg., 3scale backend-plugin 1.6.0
* move Default column to the left, and remove all values where disabled; just use a (/) icon for the TWO which are enabled.

**Comment by nickboldt** [comment]
Some things to check / fix: 

### new since 1.1 (+5):

@janus-idp/backstage-plugin-argocd
@parfuemerie-douglas/scaffolder-backend-module-azure-repositories-dynamic
@backstage/plugin-catalog-backend-module-gitlab-org
@roadiehq/scaffolder-backend-module-http-request
@janus-idp/backstage-plugin-catalog-backend-module-scaffolder-relation-processor

#### missing (-1):

@janus-idp/backstage-plugin-dynamic-plugins-info

#### Changed:

* missing link to xref:rhdh-keycloak_{context}[@janus-idp/backstage-plugin-keycloak-backend]

#### Are these correct? 

* disabled now: @backstage/plugin-kubernetes-backend
* disabled now: @janus-idp/backstage-scaffolder-backend-module-quay
* disabled now: @janus-idp/backstage-scaffolder-backend-module-regex

#### Where did this config go?

* @backstage/plugin-techdocs-backend
    `TECHDOCS_BUILDER_TYPE`
    `TECHDOCS_GENERATOR_TYPE`
    `TECHDOCS_PUBLISHER_TYPE`
    `BUCKET_NAME`
    `BUCKET_REGION_VAULT`
    `BUCKET_URL`
    `AWS_ACCESS_KEY_ID`
    `AWS_SECRET_ACCESS_KEY`

**Review by josephca — APPROVED** [review]
/lgtm
/approve

**Review by linfraze — APPROVED** [review]
/lgtm

**Pull request merged**
