### PR TITLE
RHIDP-3297: Fix curl policies example

### PR DESCRIPTION
**Pull request by dzemanov**
**Version(s):**
1.2

**Issue:**
[RHIDP-3297](https://issues.redhat.com/browse/RHIDP-3297)

### CODE REVIEW

**Review by AndrienkoAleksandr — COMMENTED** [review]
Looks good to me.

**Comment by briandooley** [comment]
@linfraze Can you look after the reviews here?

**Review by PatAKnight — APPROVED** [review]
lgtm

**Review by linfraze — APPROVED** [review]
/lgtm 

ready to merge

**Comment by linfraze** [comment]
This is good to merge, but let's wait until our 1.2.2 docs go live to boop the button :)

**Comment by hmanwani-rh** [comment]
@linfraze Is this ready to merge now?

**Pull request merged**
