### PR TITLE
RHIDP-1866: GH app id and secret variables updates

### PR DESCRIPTION
**Pull request by hmanwani-rh**
Jira: https://issues.redhat.com/browse/RHIDP-1866

### CODE REVIEW

**Review by josephca — APPROVED** [review]
/lgtm

**Comment by shipsing** [comment]
Hi @hmanwani-rh, The changes look fine. but, there are 3 more instances of the old variables (GITHUB_APP_CLIENT_ID and GITHUB_APP_CLIENT_SCRET) in the getting started guide. We need to update them globally in this doc.

**Comment by hmanwani-rh** [comment]
> Hi @hmanwani-rh, The changes look fine. but, there are 3 more instances of the old variables (GITHUB_APP_CLIENT_ID and GITHUB_APP_CLIENT_SCRET) in the getting started guide. We need to update them globally in this guide.

@shipsing Yes, Good point! However, these changes should be updated only in the GitHub authentication section, not in the entire guide. Please see Corey's comment in: https://issues.redhat.com/browse/RHIDP-1866

**Comment by shipsing** [comment]
LGTM

**Review by shipsing — APPROVED** [review]

**Pull request merged**
