### PR TITLE
chore: removed unused Gitlab authentication procedure

### PR DESCRIPTION
**Pull request by themr0c**
chore: removed unused and unsupported authentication procedure for Gittlab

**IMPORTANT: Do Not Merge - To be merged by Docs Team Only**

**Version(s):** 1.3.1

**Issue:**

**Link to docs preview:**

**Reviews:**
- [ ] SME: @ mention assignee
- [ ] QE: @ mention assignee
- [ ] Docs review: @ mention assignee
- [ ] Additional review: @mention assignee (by writer)

**Additional information:**

### CODE REVIEW

**Comment by hmanwani-rh** [comment]
@themr0c We may need this section in the future when GitLab is supported. I suggest we keep the module but exclude it for now.

**Comment by themr0c** [comment]
The content has not been reworked along the authorization book revamp. We should not reintroduce it later in current state.

**Comment by hmanwani-rh** [comment]
> The content has not been reworked along the authorization book revamp. We should not reintroduce it later in current state.


What if we need the existing information? We can always revamp it into the desired state as needed.

**Comment by themr0c** [comment]
We can get the information back from history: this PR for example. Don't keep dead code in a project. It's confusing.

**Review by hmanwani-rh — APPROVED** [review]

**Pull request merged**
