### PR TITLE
RHIDP-3971 authorization introduction

### PR DESCRIPTION
**Pull request by themr0c**
**IMPORTANT: Do Not Merge - To be merged by Docs Team Only**

**Version(s):** 1.3.1

**Issue:** https://issues.redhat.com/browse/RHIDP-3971

**Link to docs preview:** https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-632/authorization/

**Reviews:**
- [x] SME: @dzemanov 
- [x] QE: @albarbaro 
- [x] Docs review: @jmagak 
- [ ] Additional review: @mention assignee (by writer)

**Additional information:**

### CODE REVIEW

**Review by albarbaro — APPROVED** [review]
lgtm

**Comment by dzemanov** [comment]
Looks good to me

**Comment by jmagak** [comment]
LTGM, Fabrice. :)

**Review by Gerry-Forde — APPROVED** [review]

**Pull request merged**
