### PR TITLE
chore(gh action): fix to pull before pushing...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

chore(gh action): fix to pull before pushing to avoid collisions RHIDP-2842, second attempt

Signed-off-by: Nick Boldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A (or see commit message above for issue number)

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by briandooley** [comment]
RHDH docs triage: @themr0c Can you review this?

**Comment by briandooley** [comment]
@nickboldt Can you update the branch please?

**Comment by nickboldt** [comment]
@briandooley your whole team should be able to push the `Update branch`:

image

That way, the PR can be rebased, and a few mins later you have an updated PR preview too!

**Comment by briandooley** [comment]
> @briandooley your whole team should be able to push the `Update branch`:
> 
> image
> 
> That way, the PR can be rebased, and a few mins later you have an updated PR preview too!
> 
> Also since a PR like this doesn't affect anything content wise, rebasing it won't actually change the PR preview.
> 
> Plus when PRs are merged they're automatically rebased... so for the above 4 reasons, you shouldn't need me to push the button for you :D

Indeed @nickboldt. Just prefer owners of PRs to do things like that. :D

**Comment by nickboldt** [comment]
> Indeed @nickboldt. Just prefer owners of PRs to do things like that. :D

It takes less time to mash the button than to ask someone else to mash the button. Why MAKE work when you can REDUCE workload for others?

**Comment by briandooley** [comment]
@hmanwani-rh Can you review this?

**Pull request merged**
