### PR TITLE
mention backstage

### PR DESCRIPTION
**Pull request by pwright**
When I first looked at RHDH docs, I didn't realise it was based on backstage. It's common for RH products to mention the upstream in the introduction, so making this PR

### CODE REVIEW

**Review by hmanwani-rh — APPROVED** [review]

**Comment by hmanwani-rh** [comment]
@pwright Thank you for your contribution to the documentation and for making the necessary fix. Would you mind cherry-picking this change to the 1.0 and 1.1 branches so that it is reflected in our documentation?

**Comment by pwright** [comment]
@hmanwani-rh  I don't understand your request, I don't have any privileges to commit to the https://github.com/redhat-developer/red-hat-developers-documentation-rhdh repo.

**Comment by hmanwani-rh** [comment]
@pwright I'll merge this and make sure to cherry-pick the change to other branches. 
Thanks for contributing to our repo though :)

**Pull request merged**
