### PR TITLE
RHIDP-2279: Document customizing sidebar logo width

### PR DESCRIPTION
**Pull request by abrennan89**
**Versions:**
1.2+

**Jira link:**
- https://issues.redhat.com/browse/RHIDP-2279

**Preview link:**
https://redhat-developer.github.io/red-hat-developers-documentation-rhdh/pr-260/getting-started-rhdh/#ref-additional-rhdh-customizations_rhdh-getting-started

**Reviews:**
- [x] SME: @invincibleJai 
- [x] QE: @Omar-AlJaljuli 
- [x] Peer review: @linfraze

### CODE REVIEW

**Comment by invincibleJai** [comment]
cc @yashoswalyo @jerolimov

**Review by yashoswalyo — APPROVED** [review]
/approve Looks good

**Review by invincibleJai — APPROVED** [review]
LGTM

**Review by Omar-AlJaljuli — APPROVED** [review]
It looks good.

**Review by linfraze — APPROVED** [review]
One tiny change, otherwise lgtm

**Pull request merged**
